### ISSUE TITLE
invalid head of packet (0x46)

### ISSUE THREAD

**Issue by gbourlier** [Qrome/marquee-scroller#166]
Hi, 
i'm trying to install the code but something's wrong

Arduino : 1.8.12 (Windows 10), Carte : "LOLIN(WEMOS) D1 R2 & mini, 80 MHz, Flash, Disabled, All SSL ciphers (most compatible), 4M (1M SPIFFS), v2 Lower Memory, Disabled, None, All Flash Contents, 115200"

Le croquis utilise 459452 octets (43%) de l'espace de stockage de programmes. Le maximum est de 1044464 octets.
Les variables globales utilisent 45576 octets (55%) de mémoire dynamique, ce qui laisse 36344 octets pour les variables locales. Le maximum est de 81920 octets.
esptool.py v2.6
Serial port COM4
Connecting....
Chip is ESP8266EX
Features: WiFi
MAC: 00:08:ff:00:00:00
Uploading stub...
Running stub...
Traceback (most recent call last):
  File "C:\Users\bourl\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2/tools/upload.py", line 25, in <module>
    esptool.main(fakeargs)
  File "C:/Users/bourl/AppData/Local/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/tools/esptool\esptool.py", line 2670, in main
    esp = esp.run_stub()
  File "C:/Users/bourl/AppData/Local/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/tools/esptool\esptool.py", line 597, in run_stub
    p = self.read()
  File "C:/Users/bourl/AppData/Local/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/tools/esptool\esptool.py", line 277, in read
    return next(self._slip_reader)
  File "C:/Users/bourl/AppData/Local/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/tools/esptool\esptool.py", line 1889, in slip_reader
    raise FatalError('Invalid head of packet (0x%s)' % hexify(b))
esptool.FatalError: Invalid head of packet (0x46)
esptool.FatalError: Invalid head of packet (0x46)

Is someone could help me 
Thanks a lot

**Comment by Qrome** [comment]
Looks like it compiles it but an issue connecting to it over your com port.  It is saying the chip is an ESP8266EX -- maybe try selecting another board from the list?

**Comment by gbourlier** [comment]
I've tried but no way

is it possible to use this schetch with à nodemcu v3 ?

**Comment by Qrome** [comment]
Have you been able to load a test sketch on there link Blink using that selected board?   I don't think the problem is the sketch... looks like it is having issues communicating to it to load it.

**Comment by gbourlier** [comment]
I Will. It's an esp32 espressif board.
